#!/bin/sh
# shutdown - shutdown(8) lookalike for nitro

PROG="${0##*/}"
case "$PROG" in
	(halt|poweroff) nitroctl Shutdown;;
	(reboot) nitroctl Reboot;;
	(shutdown) ;;
	(*) echo "!!!!! don't know how to behave like $PROG" 1>&2
		exit -1;;
esac

single() {
  nsm runlevel single
}

abort() {
  printf '%s\n' "$1" >&2
  exit 1
}

usage() {
  abort "Usage: ${0##*/} [-fF] [-kchPr] time [warning message]"
}

action=single

amsg="shutting down"
while getopts akrhPHfFnct: opt; do
  case "$opt" in
    (a|n|H) abort "'-$opt' is not implemented";;
    (t) ;;
    (f) touch /fastboot;;
    (F) touch /forcefsck;;
    (k) action=true;;
    (c) action=cancel;;
    (h|P) action="nitroctl Shutdown";;
    (r) action="nitroctl Reboot";amsg="rebooting";;
    [?]) usage;;
  esac
done
shift $((OPTIND - 1))

[ $# -eq 0 ] && usage

time=$1; shift
message="${*:-system is $amsg}"

if [ "$action" = "cancel" ]; then
  kill "$(cat /run/nitro/shutdown.pid)"
  if [ -e /etc/nologin ] && ! [ -s /etc/nologin ]; then
    rm /etc/nologin
  fi
  echo "${*:-shutdown cancelled}" | wall
  exit
fi

touch /run/nitro/shutdown.pid 2>/dev/null || abort "Not enough permissions to execute ${0#*/}"
echo $$ >/run/nitro/shutdown.pid

case "$time" in
  (now) time=0;;
  (+*) time=${time#+};;
  (*:*) abort "absolute time is not implemented";;
  (*) abort "invalid time";;
esac

for break in 5 0; do
  [ "$time" -gt "$break" ] || continue
  [ "$break" = 0 ] && touch /etc/nologin

  printf '%s in %s minutes\n' "$message" "$time" | wall
  printf 'shutdown: sleeping for %s minutes... ' "$(( time - break ))"
  sleep $(( (time - break) * 60 ))
  time="$break"
  printf '\n'

  [ "$break" = 0 ] && rm /etc/nologin
done

printf '%s NOW action='%s'\n' "$message" | wall

$action
